Vox Fox: PrimaryNode Class Reference
PrimaryNode Class Reference
#include <PrimaryNode.h>
Public Member Functions
PrimaryNode ()
~PrimaryNode ()
PrimaryNode (glm::vec3 _origin)
PrimaryNode (PrimaryNode const &p)
PrimaryNode & operator= (PrimaryNode const &p)
PrimaryNode operator+ (PrimaryNode const &_p) const
operator + Intersection set operator (retains LHS data)
PrimaryNode operator| (PrimaryNode const &_p) const
operator | Union operator that takes two PrimaryNodes and gives PrimaryNode of union of both of them
PrimaryNode operator- (PrimaryNode const &_p) const
operator - Subtract set operator
void addVoxel (glm::vec3 _position, Voxel _voxel, SecondaryNode **io_secAccessor, LeafNode **io_leafAccessor)
addVoxel tries to add voxel to the PrimaryNode
bool isVoxel (glm::vec3 _position, SecondaryNode **io_secAccessor, LeafNode **io_leafAccessor) const
isVoxel checks if a Voxel is present within PrimaryNode at _position
glm::vec3 getOrigin () const
bool isLeaf (glm::vec3 _position, SecondaryNode **_sec, LeafNode **_leaf) const
bool isSecondary (glm::vec3 _position, SecondaryNode **_secondary) const
Public Attributes
std::vector< SecondaryNode * > m_secChildren
m_secChildren The SecondaryNode children are stored here
int idx
int idy
int idz
Private Attributes
glm::vec3 m_origin
float unitChildLength = 1.25
float m_primUnit = 10.0
float m_secUnit = 1.25
float m_leafUnit = 0.15625
float m_voxUnit = 0.01953125
Detailed Description
Definition at line 19 of file PrimaryNode.h.
Constructor & Destructor Documentation
PrimaryNode::PrimaryNode ()
Definition at line 3 of file PrimaryNode.cpp.
 {
 }
PrimaryNode::~PrimaryNode ()
Definition at line 8 of file PrimaryNode.cpp.
References m_secChildren.
 {
   for(auto & s : m_secChildren)
   {
     delete s;
   }
   m_secChildren.clear();
 }
PrimaryNode::PrimaryNode (glm::vec3 _origin)
Definition at line 17 of file PrimaryNode.cpp.
References idx, idy, idz, and m_primUnit.
                                         : m_origin(_origin)
 {
   idx = (int)(_origin[0]/m_primUnit);
   idy = (int)(_origin[1]/m_primUnit);
   idz = (int)(_origin[2]/m_primUnit);
 }
PrimaryNode::PrimaryNode (PrimaryNode const & p)
Member Function Documentation
void PrimaryNode::addVoxel (glm::vec3 _position, Voxel _voxel, SecondaryNode ** io_secAccessor, LeafNode ** io_leafAccessor)
addVoxel tries to add voxel to the PrimaryNode
Parameters
[in] _position position in worldspace of voxel
[in] _voxel the information of the voxel to be added
[in,out] io_secAccessor the secondary accessor to change (last accessed SecondaryNode)
[in,out] io_leafAccessor the leaf accessor to change (last accessed LeafNode)
Definition at line 75 of file PrimaryNode.cpp.
References m_secChildren, and unitChildLength.
 {
   bool found = false;
   for (auto &sec : m_secChildren) // access by reference to avoid copying
       {
         if(_position[0]<sec->getOrigin()[0] || _position[0]>=sec->getOrigin()[0]+unitChildLength) continue;
         if(_position[1]<sec->getOrigin()[1] || _position[1]>=sec->getOrigin()[1]+unitChildLength) continue;
         if(_position[2]<sec->getOrigin()[2] || _position[2]>=sec->getOrigin()[2]+unitChildLength) continue;
         sec->addVoxel(_position,_voxel,o_leafAccessor);
         (*o_secAccessor)=sec;
         found = true;
         break;
       }
   if(!found)
   {
     glm::vec3 newOrigin = floor(_position/unitChildLength)*unitChildLength;
     m_secChildren.push_back(new SecondaryNode(newOrigin));
     m_secChildren.back()->addVoxel(_position,_voxel,o_leafAccessor);
     (*o_secAccessor)=m_secChildren.back();
   }
 }
glm::vec3 PrimaryNode::getOrigin () const inline
Definition at line 67 of file PrimaryNode.h.
References m_origin.
 {  return m_origin; }
bool PrimaryNode::isLeaf (glm::vec3 _position, SecondaryNode ** _sec, LeafNode ** _leaf) const
Definition at line 97 of file PrimaryNode.cpp.
References getOrigin(), m_secChildren, and unitChildLength.
 {
   for (int i =0 ; i< m_secChildren.size(); ++i) // access by reference to avoid copying
   {
     if(_position[0]<m_secChildren[i]->getOrigin()[0] || _position[0]>=m_secChildren[i]->getOrigin()[0]+unitChildLength) continue;
     if(_position[1]<m_secChildren[i]->getOrigin()[1] || _position[1]>=m_secChildren[i]->getOrigin()[1]+unitChildLength) continue;
     if(_position[2]<m_secChildren[i]->getOrigin()[2] || _position[2]>=m_secChildren[i]->getOrigin()[2]+unitChildLength) continue;
     *_sec = m_secChildren[i];
     return m_secChildren[i]->isLeaf(_position,_leaf);
   }
   return false;
 }
bool PrimaryNode::isSecondary (glm::vec3 _position, SecondaryNode ** _secondary) const
Definition at line 110 of file PrimaryNode.cpp.
References getOrigin(), m_secChildren, and unitChildLength.
 {
   for (int i =0 ; i< m_secChildren.size(); ++i) // access by reference to avoid copying
   {
     if(_position[0]<m_secChildren[i]->getOrigin()[0] || _position[0]>=m_secChildren[i]->getOrigin()[0]+unitChildLength) continue;
     if(_position[1]<m_secChildren[i]->getOrigin()[1] || _position[1]>=m_secChildren[i]->getOrigin()[1]+unitChildLength) continue;
     if(_position[2]<m_secChildren[i]->getOrigin()[2] || _position[2]>=m_secChildren[i]->getOrigin()[2]+unitChildLength) continue;
     *_secondary=m_secChildren[i];
     return true;
   }
   return false;
 }
bool PrimaryNode::isVoxel (glm::vec3 _position, SecondaryNode ** io_secAccessor, LeafNode ** io_leafAccessor) const
isVoxel checks if a Voxel is present within PrimaryNode at _position
Parameters
[in] _position position in worldspace of the voxel
[in,out] io_secAccessor the secondary accessor to change (last accessed SecondaryNode)
[in,out] io_leafAccessor the leaf accessor to change (last accessed LeafNode)
Returns
if Voxel is present at _position
Definition at line 62 of file PrimaryNode.cpp.
References m_secChildren, and unitChildLength.
 {
   for (auto &sec : m_secChildren) // access by reference to avoid copying
       {
         if(_position[0]<sec->getOrigin()[0] || _position[0]>=sec->getOrigin()[0]+unitChildLength) continue;
         if(_position[1]<sec->getOrigin()[1] || _position[1]>=sec->getOrigin()[1]+unitChildLength) continue;
         if(_position[2]<sec->getOrigin()[2] || _position[2]>=sec->getOrigin()[2]+unitChildLength) continue;
         (*_secAccessor)=sec;
         return sec->isVoxel(_position,_leafAccessor);
       }
   return false;
 }
PrimaryNode PrimaryNode::operator+ (PrimaryNode const & _p) const
operator + Intersection set operator (retains LHS data)
Parameters
[in] _p The other PrimaryNode to intersect with.
Returns
Intersected PrimaryNode that retains the LHS voxel data
Definition at line 182 of file PrimaryNode.cpp.
References m_origin, m_secChildren, and PrimaryNode().
 {
   PrimaryNode retPrim = PrimaryNode(m_origin);
   for(const auto &i : m_secChildren)
   {
     for(const auto &j : _p.m_secChildren)
     {
       if(i->idx==j->idx && i->idy==j->idy && i->idz==j->idz)
       {
         retPrim.m_secChildren.push_back(new SecondaryNode(*i+*j));
       }
     }
   }
   return retPrim;
 }
PrimaryNode PrimaryNode::operator- (PrimaryNode const & _p) const
operator - Subtract set operator
Parameters
[in] _p PrimaryNode to subtract
Returns
Subtracted PrimaryNode
Definition at line 159 of file PrimaryNode.cpp.
References m_origin, m_secChildren, and PrimaryNode().
 {
   PrimaryNode retPrim = PrimaryNode(m_origin);
   for(const auto & i : m_secChildren)
   {
     bool found = false;
     for(const auto & j : _p.m_secChildren)
     {
       if(i->idx==j->idx && i->idy==j->idy && i->idz==j->idz)
       {
         retPrim.m_secChildren.push_back(new SecondaryNode(*i-*j));
         found = true;
         break;
       }
     }
     if(!found)
     {
       retPrim.m_secChildren.push_back(new SecondaryNode(*i));
     }
   }
   return retPrim;
 }
PrimaryNode & PrimaryNode::operator= (PrimaryNode const & p)
Definition at line 36 of file PrimaryNode.cpp.
References getOrigin(), idx, idy, idz, m_origin, and m_secChildren.
 {
   if(this!=&p)
   {
     // DELETE OLD DATA
     for(auto & s : m_secChildren)
     {
       delete s;
     }
     m_secChildren.clear();
     // ASSIGN NEW DATA
     for(auto &i : p.m_secChildren)
     {
       m_secChildren.push_back(new SecondaryNode(*i));
     }
     idx = p.idx;
     idy = p.idy;
     idz = p.idz;
     m_origin = p.getOrigin();
   }
   return *this;
 }
PrimaryNode PrimaryNode::operator| (PrimaryNode const & _p) const
operator | Union operator that takes two PrimaryNodes and gives PrimaryNode of union of both of them
Parameters
[in] _p RHS of operator
Returns
Union of RHS and LHS PrimaryNode
Definition at line 123 of file PrimaryNode.cpp.
References m_origin, m_secChildren, and PrimaryNode().
 {
   PrimaryNode retPrim = PrimaryNode(m_origin);
   std::vector<bool> jfound;
   for(int i =0 ; i<m_secChildren.size(); ++i)
   {
     jfound.push_back(false);
   }
   for(const auto & i : _p.m_secChildren)
   {
     bool found = false;
     for(int j =0; j<m_secChildren.size(); ++j)
     {
       if(i->idx==m_secChildren[j]->idx && i->idy==m_secChildren[j]->idy && i->idz==m_secChildren[j]->idz)
       {
         retPrim.m_secChildren.push_back(new SecondaryNode(*m_secChildren[j]|*i));
         jfound[j]=true;
         found = true;
         break;
       }
     }
     if(!found)
     {
       retPrim.m_secChildren.push_back(new SecondaryNode(*i));
     }
   }
   for(int i =0 ; i<jfound.size(); ++i)
   {
     if(!jfound[i]) retPrim.m_secChildren.push_back(new SecondaryNode(*m_secChildren[i]));
   }
   return retPrim;
 }
Member Data Documentation
int PrimaryNode::idx
Definition at line 79 of file PrimaryNode.h.
int PrimaryNode::idy
Definition at line 79 of file PrimaryNode.h.
int PrimaryNode::idz
Definition at line 79 of file PrimaryNode.h.
float PrimaryNode::m_leafUnit = 0.15625 private
Definition at line 85 of file PrimaryNode.h.
glm::vec3 PrimaryNode::m_origin private
Definition at line 81 of file PrimaryNode.h.
float PrimaryNode::m_primUnit = 10.0 private
Definition at line 83 of file PrimaryNode.h.
std::vector<SecondaryNode *> PrimaryNode::m_secChildren
m_secChildren The SecondaryNode children are stored here
Definition at line 75 of file PrimaryNode.h.
float PrimaryNode::m_secUnit = 1.25 private
Definition at line 84 of file PrimaryNode.h.
float PrimaryNode::m_voxUnit = 0.01953125 private
Definition at line 86 of file PrimaryNode.h.
float PrimaryNode::unitChildLength = 1.25 private
Definition at line 82 of file PrimaryNode.h.
The documentation for this class was generated from the following files:
PrimaryNode.h
PrimaryNode.cpp