Vox Fox: VoxFoxTree Class Reference
VoxFoxTree Class Reference
#include <VoxFoxTree.h>
Public Member Functions
VoxFoxTree ()
~VoxFoxTree ()
VoxFoxTree (const VoxFoxTree &_r)
VoxFoxTree & operator= (const VoxFoxTree &_r)
VoxFoxTree operator| (VoxFoxTree const &_r)
operator | Union operator that takes two VoxFoxTrees and gives VoxFoxTree of union of both of them
void operator|= (VoxFoxTree const &_r)
VoxFoxTree operator- (VoxFoxTree const &_r) const
operator - Subtract set operator
void operator-= (VoxFoxTree const &_r)
VoxFoxTree operator+ (VoxFoxTree const &_r) const
operator + Intersection set operator (retains LHS data)
void operator+= (VoxFoxTree const &_r)
void translate (glm::vec3 _translation)
translate Translates all voxels in the VoxFoxTree by the worldspace input
void addVoxel (glm::vec3 _position, Voxel _data)
addVoxel adds Voxel at specified _position to VoxFoxTree
bool isVoxel (glm::vec3 _position)
isVoxel checks if a Voxel is present within the VoxFoxTree at _position
void calculatePolys ()
calculatePolys This function calculates m_vertexes, m_normals and m_texturecoords for OpenGL use from VoxelData.
int getVertexSize ()
getVertexSize returns how many vertexes there are in m_vertexes
int updateVoxCount ()
std::vector< float > getVertexes ()
std::vector< float > getNormals ()
std::vector< float > getTextureCoords ()
std::vector< float > getColors ()
std::vector< PrimaryNode * > * getChildren ()
void createSphere (glm::vec3 _position, float _radius, glm::vec3 _color)
createSphere Creates a sphere in the tree
void createTorus (glm::vec3 _position, glm::vec2 _t)
createTorus Creates a torus / ring of variable radii
void createCylinder (glm::vec3 _position, glm::vec3 _axis, float _radius, float _height, glm::vec3 _color)
createCylinder Creates a cylinder in x y or z direction of variable height
void createBox (glm::vec3 _min, glm::vec3 _max, glm::vec3 _color)
createBox Creates a box
void importQuickObj (ngl::Obj *_mesh, float _size)
importQuickObj Quickly imports an polygonal .obj file to the VoxFoxTree as voxel data It is done by simply drawing in the bounding boxes of the polygons
void importObj (ngl::Obj *_mesh, glm::vec3 _color, float _size, bool _normals=true, bool _interpnormals=true)
importObj Imports a polygonal .obj file to the VoxFoxTree as voxel data.
void importTexturedObj (ngl::Obj *_mesh, ngl::Image *_texture, float _size, bool _normals=true, bool _interpnormals=true)
importObj Imports a polygonal .obj file to the VoxFoxTree as voxel data.
void drawFlatImage (glm::vec3 _position, ngl::Image *_texture, float _height)
drawFlatImage Draws a flat 1 voxel thick square with a textured image on
bool isLeaf (glm::vec3 _position)
bool isSecondary (glm::vec3 _position)
bool isPrimary (glm::vec3 _position)
PrimaryNode * getPrimAccessor ()
SecondaryNode * getSecAccessor ()
LeafNode * getLeafAccessor ()
Public Attributes
int numberOfObjects =0
float m_primUnit = 10.0
float m_secUnit = 1.25
float m_leafUnit = 0.15625
float m_voxUnit = 0.01953125
std::vector< PrimaryNode * > m_primChildren
m_primChildren The vector of PrimaryNode children.
Private Attributes
glm::vec3 min
glm::vec3 max
LeafNode * m_leafAccessor =nullptr
m_leafAccessor The last accessed LeafNode. Is updated in addVoxel and isVoxel
SecondaryNode * m_secAccessor =nullptr
m_secAccessor The last accessed SecondaryNode. Is updated in addVoxel and isVoxel
PrimaryNode * m_primAccessor =nullptr
m_primAccessor The last accessed PrimaryNode. Is updated in addVoxel and isVoxel
int numberOfVoxels =0
std::vector< float > m_vertexes
m_vertexes Vector of floats that are the x y z coordinates of the vertexes. Calculated in calculatePolygons()
std::vector< float > m_normals
m_normals Vector of floats that are x y z normals of vertexes. Made in calculatePolygons from Voxel data
std::vector< float > m_textureCoords
m_textureCoords Vector of floats that are u v coordinates of vertexes. Calculated in calculatePolygons()
std::vector< float > m_colors
m_colors Vector of floats that are r g b colour values of vertexes. Made in calculatePolygons from voxel data
Detailed Description
Definition at line 28 of file VoxFoxTree.h.
Constructor & Destructor Documentation
VoxFoxTree::VoxFoxTree ()
Definition at line 10 of file VoxFoxTree.cpp.
 {
 }
VoxFoxTree::~VoxFoxTree ()
Definition at line 22 of file VoxFoxTree.cpp.
References m_primChildren.
 {
   for(auto& p : m_primChildren)
   {
     delete p;
   }
   m_primChildren.clear();
 }
VoxFoxTree::VoxFoxTree (const VoxFoxTree & _r)
Definition at line 14 of file VoxFoxTree.cpp.
References m_primChildren.
 {
   for(auto& p : _r.m_primChildren)
   {
     m_primChildren.push_back(new PrimaryNode(*p));
   }
 }
Member Function Documentation
void VoxFoxTree::addVoxel (glm::vec3 _position, Voxel _data)
addVoxel adds Voxel at specified _position to VoxFoxTree
Parameters
[in] _position position in worldspace of the voxel
[in] _data the information of the voxel to be added (see DataStructs.h)
Definition at line 229 of file VoxFoxTree.cpp.
References PrimaryNode::addVoxel(), SecondaryNode::addVoxel(), LeafNode::addVoxel(), m_leafAccessor, m_primAccessor, m_primChildren, m_primUnit, m_secAccessor, max, and min.
 {
   if((m_leafAccessor==nullptr && m_secAccessor==nullptr) ||
      (m_leafAccessor!=nullptr && !m_leafAccessor->addVoxel(_position, _data) &&
      m_secAccessor!=nullptr && !m_secAccessor->addVoxel(_position,_data,&m_leafAccessor)))
   {
     bool found = false;
     for (auto &prim : m_primChildren) // access by reference to avoid copying
         {
           if(_position[0]<prim->getOrigin()[0] || _position[0]>=prim->getOrigin()[0]+m_primUnit) continue;
           if(_position[1]<prim->getOrigin()[1] || _position[1]>=prim->getOrigin()[1]+m_primUnit) continue;
           if(_position[2]<prim->getOrigin()[2] || _position[2]>=prim->getOrigin()[2]+m_primUnit) continue;
           m_primAccessor=prim;
           prim->addVoxel(_position,_data,&m_secAccessor,&m_leafAccessor);
           found = true;
           break;
         }
     if(!found)
     {
       glm::vec3 newOrigin = floor(_position/m_primUnit)*m_primUnit;
       m_primChildren.push_back(new PrimaryNode(newOrigin));
       m_primChildren.back()->addVoxel(_position,_data,&m_secAccessor,&m_leafAccessor);
       m_primAccessor=m_primChildren.back();
       min=glm::vec3(glm::min(min.x,newOrigin.x),glm::min(min.y,newOrigin.y),glm::min(min.z,newOrigin.z));
       max=glm::vec3(glm::max(min.x,newOrigin.x+m_primUnit),glm::max(min.y,newOrigin.y+m_primUnit),glm::max(min.z,newOrigin.z+m_primUnit));
     }
 }
 }
void VoxFoxTree::calculatePolys ()
calculatePolys This function calculates m_vertexes, m_normals and m_texturecoords for OpenGL use from VoxelData.
Definition at line 363 of file VoxFoxTree.cpp.
References isVoxel(), m_colors, m_normals, m_primChildren, m_textureCoords, m_vertexes, and m_voxUnit.
 {
     for (auto &prim : m_primChildren) // access by reference to avoid copying
     {
       for(auto &sec : prim->m_secChildren)
       {
         for(auto &leaf : sec->m_leafChildren)
         {
           int voxelindex=0;
           for(int i = 0; i<64; ++i)
           {
             for(int j = 0; j<8 ; ++j)
             {
               if(leaf->m_VoxelMap[i] & (1<<j))
               {
                 float _x = (i/8)*m_voxUnit +leaf->getOrigin()[0];
                 float _y = (i-(floor(i/8)*8))*m_voxUnit+leaf->getOrigin()[1];
                 float _z = j*m_voxUnit+leaf->getOrigin()[2];
                 float _u =  m_voxUnit;//*10;
                 int numberOfFaces =0;
                 bool blockCol = false;
                 if(leaf->m_VoxelData[voxelindex].u<-1.0f) blockCol = true;
                 float step = 0.2f;
                 // This checks whether needed to draw each face of voxel
                 // If there is voxel next to voxel then will not add the quad
                 // in between as never seen
                 // BACK FACE
                 // isVoxel
                 if((j>0 && !(leaf->m_VoxelMap[i] & (1<<(j-1))))     ||      (j==0 && !isVoxel(glm::vec3(_x,_y,_z-m_voxUnit))))
                 {
                   // 1
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   // 2
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   if(blockCol && (int)leaf->m_VoxelData.size()>=voxelindex+1)
                   {
                     for(int c =0; c<6; ++c)
                     {
                        m_colors.push_back(leaf->m_VoxelData[voxelindex].r-(step));
                        m_colors.push_back(leaf->m_VoxelData[voxelindex].g-(step));
                        m_colors.push_back(leaf->m_VoxelData[voxelindex].b-(step));
                     }
                   }
                   ++numberOfFaces;
                 }
                 // FRONT FACE
                 if((j<7 && !(leaf->m_VoxelMap[i] & (1<<(j+1))))       ||        (j==7 && !isVoxel(glm::vec3(_x,_y,_z+m_voxUnit))))
                 {
                   // 3
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   // 4
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   ++numberOfFaces;
                   if(blockCol && (int)leaf->m_VoxelData.size()>=voxelindex+1)
                   {
                     for(int c =0; c<6; ++c)
                     {
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].r-(step));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].g-(step));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].b-(step));
                     }
                   }
                 }
                 // LEFT FACE
                 if((i>7 && !(leaf->m_VoxelMap[i-8] & (1<<j)))    ||  (i<=7 && !isVoxel(glm::vec3(_x-m_voxUnit,_y,_z))))
                 {
                   // 5
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   // 6
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   if(blockCol && (int)leaf->m_VoxelData.size()>=voxelindex+1)
                   {
                     for(int c =0; c<6; ++c)
                     {
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].r-(step*0.5f));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].g-(step*0.5f));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].b-(step*0.5f));
                     }
                   }
                   ++numberOfFaces;
                 }
                 // RIGHT FACE
                 if( (i<56 && !(leaf->m_VoxelMap[i+8] & (1<<j)))  ||   (i>=56 && !isVoxel(glm::vec3(_x+m_voxUnit,_y,_z))))
                 {
                   // 7
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   // 8
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   if(blockCol && (int)leaf->m_VoxelData.size()>=voxelindex+1)
                   {
                     for(int c =0; c<6; ++c)
                     {
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].r-(step*3.0f));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].g-(step*3.0f));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].b-(step*3.0f));
                     }
                   }
                   ++numberOfFaces;
                 }
                 // TOP
                 if((i%8<7 && !(leaf->m_VoxelMap[i+1] & (1<<j)))  ||   (i%8==7 && !isVoxel(glm::vec3(_x,_y+m_voxUnit,_z))))
                 {
                   // 9
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   // 10
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y+_u);
                   m_vertexes.push_back(_z);
                   if(blockCol && (int)leaf->m_VoxelData.size()>=voxelindex+1)
                   {
                     for(int c =0; c<6; ++c)
                     {
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].r);
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].g);
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].b);
                     }
                   }
                   ++numberOfFaces;
                 }
                 // BOTTOM
                 if((i%8>0 && !(leaf->m_VoxelMap[i-1] & (1<<j)))  ||  (i%8==0 && !isVoxel(glm::vec3(_x,_y-m_voxUnit,_z))))
                 {
                   // 11
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   // 12
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z);
                   m_vertexes.push_back(_x+_u);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   m_vertexes.push_back(_x);
                   m_vertexes.push_back(_y);
                   m_vertexes.push_back(_z+_u);
                   if(blockCol && (int)leaf->m_VoxelData.size()>=voxelindex+1)
                   {
                     for(int c =0; c<6; ++c)
                     {
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].r-(step*2.5f));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].g-(step*2.5f));
                      m_colors.push_back(leaf->m_VoxelData[voxelindex].b-(step*2.5f));
                     }
                   }
                   ++numberOfFaces;
                 }
                 if((int)leaf->m_VoxelData.size()>=voxelindex+1)
                 {
                   for(int o=0; o<numberOfFaces*6; ++o)
                   {
                     m_normals.push_back(leaf->m_VoxelData[voxelindex].nx);
                     m_normals.push_back(leaf->m_VoxelData[voxelindex].ny);
                     m_normals.push_back(leaf->m_VoxelData[voxelindex].nz);
                     m_textureCoords.push_back(leaf->m_VoxelData[voxelindex].u);
                     m_textureCoords.push_back(leaf->m_VoxelData[voxelindex].v);
                     if(!blockCol)
                     {
                       m_colors.push_back(leaf->m_VoxelData[voxelindex].r);
                       m_colors.push_back(leaf->m_VoxelData[voxelindex].g);
                       m_colors.push_back(leaf->m_VoxelData[voxelindex].b);
                     }
                   }
                 }
                 ++voxelindex;
               }
             }
           }
         }
       }
 }
 }
void VoxFoxTree::createBox (glm::vec3 _min, glm::vec3 _max, glm::vec3 _color)
createBox Creates a box
Parameters
[in] _min Minimum vertex of box
[in] _max Maximum vertex of box
[in] _color Colour of box
Definition at line 706 of file VoxFoxTree.cpp.
References addVoxel(), m_voxUnit, and numberOfObjects.
 {
   numberOfObjects++;
   glm::vec3 diff = _max-_min;
   diff/=m_voxUnit;
   glm::abs(diff);
   glm::floor(diff);
   for(int x =0; x<(int)diff[0]; ++x)
   {
     for(int y =0; y<(int)diff[1]; ++y)
     {
       for(int z =0; z<(int)diff[2]; ++z)
       {
         glm::vec3 pos = _min + (glm::vec3(x,y,z)*m_voxUnit);
         Voxel toBeInserted = Voxel(_color[0],_color[1],_color[2]);
         toBeInserted.nx = 2.0f;
         toBeInserted.u = -2.0f;
         addVoxel(pos,toBeInserted);
       }
     }
   }
 }
void VoxFoxTree::createCylinder (glm::vec3 _position, glm::vec3 _axis, float _radius, float _height, glm::vec3 _color)
createCylinder Creates a cylinder in x y or z direction of variable height
Parameters
[in] _position Centre of cylinder
[in] _axis Direction to create cylinder
[in] _radius Radius of cylinder in worldspace
[in] _height Height of cylinder
[in] _color Color of cylinder (0.0f-1.0f)
Definition at line 334 of file VoxFoxTree.cpp.
References addVoxel(), m_voxUnit, and numberOfObjects.
 {
   numberOfObjects++;
   int heightvox = (int)(_height/m_voxUnit);
   int diameter = (int)((_radius*2.0f)/m_voxUnit);
   glm::vec2 h = glm::vec2(_radius,_height);
     for(int x=-diameter/2; x<diameter/2; ++x)
     {
       for(int y=-heightvox/2; y<heightvox/2; ++y)
       {
         for(int z=-diameter/2; z<diameter/2; ++z)
         {
           glm::vec3 p = glm::vec3(x,y,z)*m_voxUnit;
           glm::vec2 d = glm::abs(glm::vec2(glm::length(glm::vec2(p.x,p.z)),p.y)) - h;
           if(glm::min(glm::max(d.x,d.y),0.0f) + glm::length(glm::max(d,0.0f))<0.0f)
           {
             Voxel toBeInserted = Voxel(_color[0],_color[1],_color[2]);
             if(_axis[1]>0.0f) addVoxel(p+_position,toBeInserted);
             else if(_axis[0]>0.0f) addVoxel(glm::vec3(p.y,p.z,p.x)+_position,toBeInserted);
             else if(_axis[2]>0.0f) addVoxel(glm::vec3(p.z,p.x,p.y)+_position,toBeInserted);
           }
         }
       }
     }
 }
void VoxFoxTree::createSphere (glm::vec3 _position, float _radius, glm::vec3 _color)
createSphere Creates a sphere in the tree
Parameters
[in] _position Centre of sphere
[in] _radius Radius of sphere (worldspace)
[in] _color RGB color of sphere (0.0f-1.0f)
Definition at line 658 of file VoxFoxTree.cpp.
References addVoxel(), m_voxUnit, numberOfObjects, Voxel::nx, and Voxel::u.
 {
   numberOfObjects++;
   int voxRadius = (int)(_radius/m_voxUnit);
   for(int x = -voxRadius; x<voxRadius; ++x)
   {
     for(int y = -voxRadius; y<voxRadius; ++y)
       {
       for(int z = -voxRadius; z<voxRadius; ++z)
         {
           glm::vec3 pos = glm::vec3(x,y,z)*m_voxUnit;
           if(glm::length(pos) < _radius)
           {
             Voxel toBe = Voxel(_color[0],_color[1],_color[2]);
             toBe.nx = 2.0f;
             toBe.u = -2.0f;
             addVoxel(pos+_position,toBe);
           }
         }
       }
   }
 }
void VoxFoxTree::createTorus (glm::vec3 _position, glm::vec2 _t)
createTorus Creates a torus / ring of variable radii
Parameters
[in] _position Centre point of the torus to create
[in] _t The two radius (inner and outter) of the torus
Definition at line 682 of file VoxFoxTree.cpp.
References addVoxel(), m_voxUnit, and numberOfObjects.
 {
   numberOfObjects++;
   int _radius = (_t.y / m_voxUnit) + 1;
   for(int x = -_radius; x<_radius; ++x)
   {
     for(int y = -_radius; y<_radius; ++y)
       {
       for(int z = -_radius; z<_radius; ++z)
         {
           glm::vec3 pos = glm::vec3(x,y,z)*m_voxUnit;
           pos+=_position;
           glm::vec2 q = glm::vec2(glm::length(glm::vec2(pos.x,pos.z))-_t.x,pos.y);
           if(glm::length(q) < _t.y)
           {
             addVoxel(pos,Voxel());
           }
         }
       }
   }
 }
void VoxFoxTree::drawFlatImage (glm::vec3 _position, ngl::Image * _texture, float _height)
drawFlatImage Draws a flat 1 voxel thick square with a textured image on
Parameters
_position Centre of image plane
_texture texture to use
_height The height of the square
Definition at line 186 of file VoxFoxTree.cpp.
References addVoxel(), Voxel::b, Voxel::g, m_voxUnit, numberOfObjects, Voxel::nx, and Voxel::r.
 {
   numberOfObjects++;
   int steps = glm::floor(_height/m_voxUnit);
   glm::vec3 currentPos = _position + glm::vec3(-_height/2.0f,-_height/2.0f,0.0f);
   for(int i =0; i<steps; ++i)
   {
     currentPos+=glm::vec3(m_voxUnit,0.0f,0.0f);
     currentPos[1]=-_height/2.0f + _position[1];
     for(int j=0; j<steps; ++j)
     {
       currentPos+=glm::vec3(0.0f,m_voxUnit,0.0f);
       Voxel toBeInserted = Voxel();
       ngl::Colour voxCol= _texture->getColour(((float)i)/((float)steps),((float)j)/((float)steps));
       toBeInserted.r = voxCol.m_r/255.0f;
       toBeInserted.g = voxCol.m_g/255.0f;
       toBeInserted.b = voxCol.m_b/255.0f;
       toBeInserted.nx = 2.0f;
       if((int)voxCol.m_a>254)
       {
         addVoxel(currentPos,toBeInserted);
       }
     }
   }
 }
std::vector<PrimaryNode *>* VoxFoxTree::getChildren () inline
Definition at line 98 of file VoxFoxTree.h.
References m_primChildren.
 {return &m_primChildren;}
std::vector< float > VoxFoxTree::getColors ()
Definition at line 176 of file VoxFoxTree.cpp.
References m_colors.
 {
   return m_colors;
 }
LeafNode* VoxFoxTree::getLeafAccessor () inline
Definition at line 181 of file VoxFoxTree.h.
References m_leafAccessor.
 {return m_leafAccessor;}
std::vector< float > VoxFoxTree::getNormals ()
Definition at line 166 of file VoxFoxTree.cpp.
References m_normals.
 {
   return m_normals;
 }
PrimaryNode* VoxFoxTree::getPrimAccessor () inline
Definition at line 179 of file VoxFoxTree.h.
References m_primAccessor.
 {return m_primAccessor;}
SecondaryNode* VoxFoxTree::getSecAccessor () inline
Definition at line 180 of file VoxFoxTree.h.
References m_secAccessor.
 {return m_secAccessor;}
std::vector< float > VoxFoxTree::getTextureCoords ()
Definition at line 171 of file VoxFoxTree.cpp.
References m_textureCoords.
 {
   return m_textureCoords;
 }
std::vector< float > VoxFoxTree::getVertexes ()
Definition at line 160 of file VoxFoxTree.cpp.
References m_vertexes.
 {
   return m_vertexes;
 }
int VoxFoxTree::getVertexSize ()
getVertexSize returns how many vertexes there are in m_vertexes
Returns
m_vertexes.size()
Definition at line 181 of file VoxFoxTree.cpp.
References m_vertexes.
 {
   return m_vertexes.size();
 }
void VoxFoxTree::importObj (ngl::Obj * _mesh, glm::vec3 _color, float _size, bool _normals = true, bool _interpnormals = true)
importObj Imports a polygonal .obj file to the VoxFoxTree as voxel data.
Parameters
[in] _mesh The ngl::Obj object of the mesh
[in] _color The color of the object
[in] _normals This tells us we want normals used in shader and calculated
[in] _interpnormals This tells us to interpolate the normals in fragments between vertexes
Definition at line 761 of file VoxFoxTree.cpp.
References addVoxel(), Voxel::b, Voxel::g, m_voxUnit, numberOfObjects, Voxel::r, Voxel::u, and Voxel::v.
 {
   if(_size < m_voxUnit) return;
   numberOfObjects++;
   std::vector<ngl::Vec3> verts = _mesh->getVertexList();
   std::vector<ngl::Face> objFaceList = _mesh->getFaceList();
   _mesh->calcDimensions();
   ngl::BBox boundingBox = _mesh->getBBox();
   float meshheight = boundingBox.height();
   float scale = _size/meshheight;
   ngl::Vec3 centre = boundingBox.center();
   std::vector<ngl::Vec3> vertNormals = std::vector<ngl::Vec3>(verts.size());
   std::fill(vertNormals.begin(), vertNormals.end(), ngl::Vec3(0.0f,0.0f,0.0f));
   std::vector<int> numberOfFacesPerVert = std::vector<int>(verts.size());
   std::fill(numberOfFacesPerVert.begin(), numberOfFacesPerVert.end(), 0);
   std::vector<ngl::Vec3> vertTex = _mesh->getTextureCordList();
   if(_interpnormals && _normals)
   {
     for(int i = 0; i<objFaceList.size(); ++i)
     {
       ngl::Vec3 tmpNormal;
       tmpNormal = (verts[objFaceList[i].m_vert[1]]-verts[objFaceList[i].m_vert[0]]).cross(verts[objFaceList[i].m_vert[2]]-verts[objFaceList[i].m_vert[0]]);
       tmpNormal.normalize();
       for(int j =0; j<objFaceList[i].m_vert.size(); ++j)
       {
         vertNormals[objFaceList[i].m_vert[j]] += tmpNormal;
         numberOfFacesPerVert[objFaceList[i].m_vert[j]]++;
       }
     }
     for(int i =0; i<(int)vertNormals.size(); ++i)
     {
       vertNormals[i]= vertNormals[i]/numberOfFacesPerVert[i] ;
       vertNormals[i].normalize();
     }
   }
   for(std::vector<ngl::Face>::iterator itr=objFaceList.begin(); itr!=objFaceList.end(); ++itr)
   {
     if(itr->m_vert.size()==3)
     {
       //-------------------------VERTEXES----------------------------
       ngl::Vec3 a, b, c, e1;
       a = verts[itr->m_vert[0]]*scale - centre;
       b = verts[itr->m_vert[1]]*scale - centre;
       c = verts[itr->m_vert[2]]*scale - centre;
       e1 = b - a;
       //--------------------------NORMALS-----------------------------
       ngl::Vec3 na, nb, nc;
       ngl::Vec3 tmpNormal;
       if(_interpnormals && _normals)
       {
         na = vertNormals[itr->m_vert[0]];
         nb = vertNormals[itr->m_vert[1]];
         nc = vertNormals[itr->m_vert[2]];
       }
       else if(_normals)
       {
         tmpNormal = (verts[itr->m_vert[1]]-verts[itr->m_vert[0]]).cross(verts[itr->m_vert[2]]-verts[itr->m_vert[0]]);
         tmpNormal.normalize();
       }
       int steps = std::ceil(e1.length()/m_voxUnit);
       ngl::Vec3 vecStep = e1/(2*steps); // scaled
       for(int i =0; i<(steps+1)*2; ++i) //scaled
       {
         ngl::Vec3 pos = a+(vecStep*i);
         ngl::Vec3 posnormal = ngl::lerp(na,nb,((float)i)/((float)(((steps+1)*2)-1)));
         //ngl::Vec2 posUV = ;
         ngl::Vec3 line = c-pos;
         int jsteps = std::ceil(line.length()/m_voxUnit);
         if(i!=steps)
         {
           if(i%2==1) jsteps/=2;
           else if(i%4==2) jsteps*=0.75;
           else if(i%8==4) jsteps*=0.875;
         }
         ngl::Vec3 mystep = line*(m_voxUnit / (3*line.length())); //scaled
         for(int j = 0; j<jsteps*3; ++j) //scaled
         {
           float inNX, inNY, inNZ;
           float inU, inV;
           if(_interpnormals && _normals)
           {
             ngl::Vec3 posnormal2 = lerp(posnormal,nc,((float)j)/((float)((jsteps*3) - 1)));
             inNX = posnormal2.m_x;
             inNY = posnormal2.m_y;
             inNZ = posnormal2.m_z;
           }
           else if(_normals)
           {
             inNX = tmpNormal.m_x;
             inNY = tmpNormal.m_y;
             inNZ = tmpNormal.m_z;
           }
           else
           {
             inNX = 2.0f;
             inNY = 2.0f;
             inNZ = 2.0f;
           }
           Voxel toinsert = Voxel(inNX,inNY,inNZ,inU,inV);
           toinsert.r = _color[0];
           toinsert.g = _color[1];
           toinsert.b = _color[2];
           toinsert.u=inU;
           toinsert.v=inV;
           addVoxel(glm::vec3(pos.m_x,pos.m_y,pos.m_z),toinsert);
           pos = pos + mystep;
         }
       }
     }
  }
 }
void VoxFoxTree::importQuickObj (ngl::Obj * _mesh, float _size)
importQuickObj Quickly imports an polygonal .obj file to the VoxFoxTree as voxel data It is done by simply drawing in the bounding boxes of the polygons
Parameters
[in] _mesh The ngl::Obj object of the mesh
[in] _size Height of the object in the worldspace
Definition at line 729 of file VoxFoxTree.cpp.
References createBox(), max, and min.
 {
   std::vector<ngl::Vec3> verts = _mesh->getVertexList();
   std::vector<ngl::Face> objFaceList = _mesh->getFaceList();
   _mesh->calcDimensions();
   ngl::BBox boundingBox = _mesh->getBBox();
   float meshheight = boundingBox.height();
   float scale = _size/meshheight;
   ngl::Vec3 centre = boundingBox.center();
   for(std::vector<ngl::Face>::iterator itr=objFaceList.begin(); itr!=objFaceList.end(); ++itr)
   {
     int numVertexInFace = itr->m_vert.size();
     ngl::Vec3 min = verts[itr->m_vert[0]];
     ngl::Vec3 max = min;
     for(int i=1;i<numVertexInFace;i++)
     {
       if(verts[itr->m_vert[i]].m_x<min.m_x) {min.m_x=verts[itr->m_vert[i]].m_x*scale - centre.m_x;}
       if(verts[itr->m_vert[i]].m_y<min.m_y) {min.m_y=verts[itr->m_vert[i]].m_y*scale - centre.m_y;}
       if(verts[itr->m_vert[i]].m_z<min.m_z) {min.m_z=verts[itr->m_vert[i]].m_z*scale - centre.m_z;}
       if(verts[itr->m_vert[i]].m_x>max.m_x) {max.m_x=verts[itr->m_vert[i]].m_x*scale - centre.m_x;}
       if(verts[itr->m_vert[i]].m_y>max.m_y) {max.m_y=verts[itr->m_vert[i]].m_y*scale - centre.m_y;}
       if(verts[itr->m_vert[i]].m_z>max.m_z) {max.m_z=verts[itr->m_vert[i]].m_z*scale - centre.m_z;}
     }
     if(numVertexInFace==3) createBox(glm::vec3(min.m_x,min.m_y,min.m_z),glm::vec3(max.m_x,max.m_y,max.m_z),glm::vec3(1.0f,0.0f,0.0f));
     }
 }
void VoxFoxTree::importTexturedObj (ngl::Obj * _mesh, ngl::Image * _texture, float _size, bool _normals = true, bool _interpnormals = true)
importObj Imports a polygonal .obj file to the VoxFoxTree as voxel data.
Parameters
[in] _mesh The ngl::Obj object of the mesh
[in] _texture The texture of the object
[in] _normals This tells us we want normals used in shader and calculated
[in] _interpnormals This tells us to interpolate the normals in fragments between vertexes
Definition at line 894 of file VoxFoxTree.cpp.
References addVoxel(), Voxel::b, Voxel::g, m_voxUnit, numberOfObjects, Voxel::r, Voxel::u, and Voxel::v.
 {
   if(_size < m_voxUnit) return;
   numberOfObjects++;
   std::vector<ngl::Vec3> verts = _mesh->getVertexList();
   std::vector<ngl::Face> objFaceList = _mesh->getFaceList();
   //std::vector<ngl::Vec3> normalList = _mesh->getNormalList();
   _mesh->calcDimensions();
   ngl::BBox boundingBox = _mesh->getBBox();
   float meshheight = boundingBox.height();
   float scale = _size/meshheight;
   ngl::Vec3 centre = boundingBox.center();
   std::vector<ngl::Vec3> vertNormals = std::vector<ngl::Vec3>(verts.size());
   std::fill(vertNormals.begin(), vertNormals.end(), ngl::Vec3(0.0f,0.0f,0.0f));
   std::vector<int> numberOfFacesPerVert = std::vector<int>(verts.size());
   std::fill(numberOfFacesPerVert.begin(), numberOfFacesPerVert.end(), 0);
   std::vector<ngl::Vec3> vertTex = _mesh->getTextureCordList();
   if(_interpnormals && _normals)
   {
     for(int i = 0; i<objFaceList.size(); ++i)
     {
       ngl::Vec3 tmpNormal;
       tmpNormal = (verts[objFaceList[i].m_vert[1]]-verts[objFaceList[i].m_vert[0]]).cross(verts[objFaceList[i].m_vert[2]]-verts[objFaceList[i].m_vert[0]]);
       tmpNormal.normalize();
       for(int j =0; j<objFaceList[i].m_vert.size(); ++j)
       {
         vertNormals[objFaceList[i].m_vert[j]] += tmpNormal;
         numberOfFacesPerVert[objFaceList[i].m_vert[j]]++;
       }
     }
     for(int i =0; i<(int)vertNormals.size(); ++i)
     {
       vertNormals[i]= vertNormals[i]/numberOfFacesPerVert[i] ;
       vertNormals[i].normalize();
     }
   }
   for(std::vector<ngl::Face>::iterator itr=objFaceList.begin(); itr!=objFaceList.end(); ++itr)
   {
     if(itr->m_vert.size()==3)
     {
       //-------------------------VERTEXES----------------------------
       ngl::Vec3 a, b, c, e1;
       a = verts[itr->m_vert[0]]*scale - centre;
       b = verts[itr->m_vert[1]]*scale - centre;
       c = verts[itr->m_vert[2]]*scale - centre;
       e1 = b - a;
       ngl::Vec3 ta, tb, tc;
       ta = vertTex[itr->m_tex[0]];
       tb = vertTex[itr->m_tex[1]];
       tc = vertTex[itr->m_tex[2]];
       //--------------------------NORMALS-----------------------------
       ngl::Vec3 na, nb, nc;
       ngl::Vec3 tmpNormal;
       if(_interpnormals && _normals)
       {
         na = vertNormals[itr->m_vert[0]];
         nb = vertNormals[itr->m_vert[1]];
         nc = vertNormals[itr->m_vert[2]];
       }
       else if(_normals)
       {
         tmpNormal = (verts[itr->m_vert[1]]-verts[itr->m_vert[0]]).cross(verts[itr->m_vert[2]]-verts[itr->m_vert[0]]);
         tmpNormal.normalize();
       }
       int steps = std::ceil(e1.length()/m_voxUnit);
       ngl::Vec3 vecStep = e1/(2*steps); // scaled
       for(int i =0; i<(steps+1)*2; ++i) //scaled
       {
         ngl::Vec3 pos = a+(vecStep*i);
         ngl::Vec3 posnormal = ngl::lerp(na,nb,((float)i)/((float)(((steps+1)*2)-1)));
         ngl::Vec3 postexture = ngl::lerp(ta,tb,((float)i)/((float)(((steps+1)*2)-1)));
         //ngl::Vec2 posUV = ;
         ngl::Vec3 line = c-pos;
         int jsteps = std::ceil(line.length()/m_voxUnit);
         if(i!=steps)
         {
           if(i%2==1) jsteps/=2;
           else if(i%4==2) jsteps*=0.75;
           else if(i%8==4) jsteps*=0.875;
         }
         ngl::Vec3 mystep = line*(m_voxUnit / (3*line.length())); //scaled
         for(int j = 0; j<jsteps*3; ++j) //scaled
         {
           float inNX, inNY, inNZ;
           float inU, inV;
           if(_interpnormals && _normals)
           {
             ngl::Vec3 posnormal2 = lerp(posnormal,nc,((float)j)/((float)((jsteps*3) - 1)));
             inNX = posnormal2.m_x;
             inNY = posnormal2.m_y;
             inNZ = posnormal2.m_z;
           }
           else if(_normals)
           {
             inNX = tmpNormal.m_x;
             inNY = tmpNormal.m_y;
             inNZ = tmpNormal.m_z;
           }
           else
           {
             inNX = 2.0f;
             inNY = 2.0f;
             inNZ = 2.0f;
           }
           Voxel toinsert = Voxel(inNX,inNY,inNZ,inU,inV);
             // Get RGB value from texture
             // Put in shader as FragmentColor
             ngl::Vec3 postexture2 = lerp(postexture,tc,((float)j)/((float)((jsteps*3) - 1)));
             inU = postexture2.m_x - (int)postexture2.m_x;
             inV = postexture2.m_y - (int)postexture2.m_y;
             toinsert.r = (float)_texture->getColour(inU,inV).m_r/255.0f;
             toinsert.g = (float)_texture->getColour(inU,inV).m_g/255.0f;
             toinsert.b = (float)_texture->getColour(inU,inV).m_b/255.0f;
           // We retain UVs if not using my specific shader
           toinsert.u=inU;
           toinsert.v=inV;
           addVoxel(glm::vec3(pos.m_x,pos.m_y,pos.m_z),toinsert);
           pos = pos + mystep;
         }
       }
     }
  }
 }
bool VoxFoxTree::isLeaf (glm::vec3 _position)
Definition at line 259 of file VoxFoxTree.cpp.
References m_leafAccessor, m_primChildren, m_primUnit, and m_secAccessor.
 {
   for (auto& prim: m_primChildren) // access by reference to avoid copying
   {
     if(_position[0]<prim->getOrigin()[0] || _position[0]>=prim->getOrigin()[0]+m_primUnit) continue;
     if(_position[1]<prim->getOrigin()[1] || _position[1]>=prim->getOrigin()[1]+m_primUnit) continue;
     if(_position[2]<prim->getOrigin()[2] || _position[2]>=prim->getOrigin()[2]+m_primUnit) continue;
     return prim->isLeaf(_position,&m_secAccessor,&m_leafAccessor);
   }
   return false;
 }
bool VoxFoxTree::isPrimary (glm::vec3 _position)
Definition at line 283 of file VoxFoxTree.cpp.
References m_primAccessor, m_primChildren, and m_primUnit.
 {
   for (auto& prim: m_primChildren) // access by reference to avoid copying
   {
     if(_position[0]<prim->getOrigin()[0] || _position[0]>=prim->getOrigin()[0]+m_primUnit) continue;
     if(_position[1]<prim->getOrigin()[1] || _position[1]>=prim->getOrigin()[1]+m_primUnit) continue;
     if(_position[2]<prim->getOrigin()[2] || _position[2]>=prim->getOrigin()[2]+m_primUnit) continue;
     m_primAccessor=prim;
     return true;
   }
   return false;
 }
bool VoxFoxTree::isSecondary (glm::vec3 _position)
Definition at line 271 of file VoxFoxTree.cpp.
References m_primChildren, m_primUnit, and m_secAccessor.
 {
   for (auto& prim: m_primChildren) // access by reference to avoid copying
   {
     if(_position[0]<prim->getOrigin()[0] || _position[0]>=prim->getOrigin()[0]+m_primUnit) continue;
     if(_position[1]<prim->getOrigin()[1] || _position[1]>=prim->getOrigin()[1]+m_primUnit) continue;
     if(_position[2]<prim->getOrigin()[2] || _position[2]>=prim->getOrigin()[2]+m_primUnit) continue;
     return prim->isSecondary(_position,&m_secAccessor);
   }
   return false;
 }
bool VoxFoxTree::isVoxel (glm::vec3 _position)
isVoxel checks if a Voxel is present within the VoxFoxTree at _position
Parameters
[in] _position position in worldspace of the voxel
Returns
if Voxel is present at _position
Definition at line 213 of file VoxFoxTree.cpp.
References SecondaryNode::isVoxel(), PrimaryNode::isVoxel(), LeafNode::isVoxel(), m_leafAccessor, m_primAccessor, m_primChildren, m_primUnit, and m_secAccessor.
 {
   if(m_leafAccessor!=nullptr && m_leafAccessor->isVoxel(_position)) return true;
   else if ( m_secAccessor!=nullptr && m_secAccessor->isVoxel(_position,&m_leafAccessor)) return true;
   for (auto &prim : m_primChildren) // access by reference to avoid copying
       {
         if(_position[0]<prim->getOrigin()[0] || _position[0]>=prim->getOrigin()[0]+m_primUnit) continue;
         if(_position[1]<prim->getOrigin()[1] || _position[1]>=prim->getOrigin()[1]+m_primUnit) continue;
         if(_position[2]<prim->getOrigin()[2] || _position[2]>=prim->getOrigin()[2]+m_primUnit) continue;
         m_primAccessor=prim;
         return prim->isVoxel(_position,&m_secAccessor,&m_leafAccessor);
       }
   return false;
 }
VoxFoxTree VoxFoxTree::operator+ (VoxFoxTree const & _r) const
operator + Intersection set operator (retains LHS data)
Parameters
[in] _r The other tree to intersect with.
Returns
Intersected tree that retains the LHS voxel data
Definition at line 138 of file VoxFoxTree.cpp.
References m_primChildren, and PrimaryNode::m_secChildren.
 {
   VoxFoxTree retRoot;
   for(auto & i : m_primChildren)
   {
     for(auto & j : _v.m_primChildren)
     {
       if(i->idx==j->idx && i->idy==j->idy && i->idz==j->idz)
       {
         PrimaryNode testNode = PrimaryNode(*i+*j);
         if(testNode.m_secChildren.size()!=0) retRoot.m_primChildren.push_back(new PrimaryNode(testNode));
       }
     }
   }
   return retRoot;
 }
void VoxFoxTree::operator+= (VoxFoxTree const & _r)
Definition at line 155 of file VoxFoxTree.cpp.
 {
   (*this) = (*this) + (_r);
 }
VoxFoxTree VoxFoxTree::operator- (VoxFoxTree const & _r) const
operator - Subtract set operator
Parameters
[in] _r Tree to subtract
Returns
Subtracted tree
Definition at line 109 of file VoxFoxTree.cpp.
References m_primChildren, and PrimaryNode::m_secChildren.
 {
   VoxFoxTree retRoot;
   for(auto & i : m_primChildren)
   {
     bool found = false;
     for(auto & j : _r.m_primChildren)
     {
       if(i->idx==j->idx && i->idy==j->idy && i->idz==j->idz)
       {
         PrimaryNode testNode = PrimaryNode(*i-*j);
         if(testNode.m_secChildren.size()!=0) retRoot.m_primChildren.push_back(new PrimaryNode(testNode));
         found = true;
         break;
       }
     }
     if(!found)
     {
       retRoot.m_primChildren.push_back(new PrimaryNode(*i));
     }
   }
   return retRoot;
 }
void VoxFoxTree::operator-= (VoxFoxTree const & _r)
Definition at line 133 of file VoxFoxTree.cpp.
 {
   (*this) = (*this) - (_r);
 }
VoxFoxTree & VoxFoxTree::operator= (const VoxFoxTree & _r)
Definition at line 32 of file VoxFoxTree.cpp.
References m_colors, m_leafAccessor, m_normals, m_primAccessor, m_primChildren, m_secAccessor, m_textureCoords, and m_vertexes.
 {
   if(this!=&_r)
   {
     // DELETE OLD DATA
     for(auto& p : m_primChildren)
     {
       delete p;
     }
     m_primChildren.clear();
     m_vertexes.clear();
     m_normals.clear();
     m_textureCoords.clear();
     m_colors.clear();
     m_leafAccessor=nullptr;
     m_primAccessor=nullptr;
     m_secAccessor=nullptr;
     // INSERT NEW DATA
     for(auto& p : _r.m_primChildren)
     {
       m_primChildren.push_back(new PrimaryNode(*p));
     }
     m_vertexes=_r.m_vertexes;
     m_normals= _r.m_normals;
     m_textureCoords = _r.m_textureCoords;
     m_colors = _r.m_colors;
   }
   return *this;
 }
VoxFoxTree VoxFoxTree::operator| (VoxFoxTree const & _r)
operator | Union operator that takes two VoxFoxTrees and gives VoxFoxTree of union of both of them
Parameters
[in] _r RHS of operator
Returns
Union of RHS and LHS VoxFoxTree
Definition at line 66 of file VoxFoxTree.cpp.
References m_primChildren, and numberOfObjects.
 {
   VoxFoxTree retRoot;
   std::vector<bool> jfound;
   for(int i =0 ; i<m_primChildren.size(); ++i)
   {
     jfound.push_back(false);
   }
   for(auto & i : _r.m_primChildren)
   {
     bool found = false;
     for(int j =0; j<m_primChildren.size(); ++j)
     {
       if(i->idx==m_primChildren[j]->idx && i->idy==m_primChildren[j]->idy && i->idz==m_primChildren[j]->idz)
       {
         retRoot.m_primChildren.push_back(new PrimaryNode(*m_primChildren[j]|*i));
         jfound[j]=true;
         found = true;
         break;
       }
     }
     if(!found)
     {
       retRoot.m_primChildren.push_back(new PrimaryNode(*i));
     }
   }
   for(int i =0 ; i<jfound.size(); ++i)
   {
     if(!jfound[i]) retRoot.m_primChildren.push_back(new PrimaryNode(*m_primChildren[i]));
   }
   retRoot.numberOfObjects=_r.numberOfObjects + numberOfObjects;
   return retRoot;
 }
void VoxFoxTree::operator|= (VoxFoxTree const & _r)
Definition at line 103 of file VoxFoxTree.cpp.
References numberOfObjects.
 {
   (*this) = (*this) | (_r);
   (*this).numberOfObjects+=(_r).numberOfObjects;
 }
void VoxFoxTree::translate (glm::vec3 _translation)
translate Translates all voxels in the VoxFoxTree by the worldspace input
Parameters
[in] _translation amount to translate the VoxFoxTree
Definition at line 296 of file VoxFoxTree.cpp.
References addVoxel(), m_leafAccessor, m_primAccessor, m_primChildren, m_secAccessor, and m_voxUnit.
 {
   std::vector<glm::vec3> ourTranslatedPositions;
   std::vector<Voxel> ourTranslatedVoxels;
   // This is the simple approach.
   // It got extremely complicated if I tried a "smarter" approach by moving the origins and voxels by hand.
   // More complicated than the hardest sudoku.
   for (auto &prim : m_primChildren)
   {
     for(auto &sec : prim->m_secChildren)
     {
       for(auto &leaf : sec->m_leafChildren)
       {
         for(auto &vox : leaf->m_VoxelData)
         {
           ourTranslatedVoxels.push_back(vox);
           float x = (int)(vox.index/(8*8));
           float y = (int)(vox.index/8)-x*8;
           float z = vox.index - x*8*8 - y*8;
           glm::vec3 ourPosition = glm::vec3(x,y,z)*m_voxUnit + leaf->getOrigin() + _translation;
           ourTranslatedPositions.push_back(ourPosition);
         }
       }
     }
     delete prim;
   }
   m_primChildren.clear();
   m_primAccessor=nullptr;
   m_secAccessor=nullptr;
   m_leafAccessor=nullptr;
   for(int i =0; i<ourTranslatedPositions.size(); ++i)
   {
     addVoxel(ourTranslatedPositions[i],ourTranslatedVoxels[i]);
   }
 }
int VoxFoxTree::updateVoxCount ()
Definition at line 1040 of file VoxFoxTree.cpp.
References m_primChildren, and numberOfVoxels.
 {
   // Hopefully this is correct!
   const unsigned char oneBits[] = {0,1,1,2,1,2,2,3,1,2,2,3,2,3,3,4};
   numberOfVoxels=0;
   for (auto &prim : m_primChildren) // access by reference to avoid copying
   {
     for(auto &sec : prim->m_secChildren)
     {
       for(auto &leaf : sec->m_leafChildren)
       {
         numberOfVoxels+=leaf->m_VoxelData.size();
       }
     }
   }
   return numberOfVoxels;
 }
Member Data Documentation
std::vector<float> VoxFoxTree::m_colors private
m_colors Vector of floats that are r g b colour values of vertexes. Made in calculatePolygons from voxel data
Definition at line 227 of file VoxFoxTree.h.
LeafNode* VoxFoxTree::m_leafAccessor =nullptr private
m_leafAccessor The last accessed LeafNode. Is updated in addVoxel and isVoxel
Definition at line 199 of file VoxFoxTree.h.
float VoxFoxTree::m_leafUnit = 0.15625
Definition at line 185 of file VoxFoxTree.h.
std::vector<float> VoxFoxTree::m_normals private
m_normals Vector of floats that are x y z normals of vertexes. Made in calculatePolygons from Voxel data
Definition at line 219 of file VoxFoxTree.h.
PrimaryNode* VoxFoxTree::m_primAccessor =nullptr private
m_primAccessor The last accessed PrimaryNode. Is updated in addVoxel and isVoxel
Definition at line 207 of file VoxFoxTree.h.
std::vector<PrimaryNode *> VoxFoxTree::m_primChildren
m_primChildren The vector of PrimaryNode children.
Definition at line 191 of file VoxFoxTree.h.
float VoxFoxTree::m_primUnit = 10.0
Definition at line 183 of file VoxFoxTree.h.
SecondaryNode* VoxFoxTree::m_secAccessor =nullptr private
m_secAccessor The last accessed SecondaryNode. Is updated in addVoxel and isVoxel
Definition at line 203 of file VoxFoxTree.h.
float VoxFoxTree::m_secUnit = 1.25
Definition at line 184 of file VoxFoxTree.h.
std::vector<float> VoxFoxTree::m_textureCoords private
m_textureCoords Vector of floats that are u v coordinates of vertexes. Calculated in calculatePolygons()
Definition at line 223 of file VoxFoxTree.h.
std::vector<float> VoxFoxTree::m_vertexes private
m_vertexes Vector of floats that are the x y z coordinates of the vertexes. Calculated in calculatePolygons()
Definition at line 215 of file VoxFoxTree.h.
float VoxFoxTree::m_voxUnit = 0.01953125
Definition at line 186 of file VoxFoxTree.h.
glm::vec3 VoxFoxTree::max private
Definition at line 194 of file VoxFoxTree.h.
glm::vec3 VoxFoxTree::min private
Definition at line 194 of file VoxFoxTree.h.
int VoxFoxTree::numberOfObjects =0
Definition at line 172 of file VoxFoxTree.h.
int VoxFoxTree::numberOfVoxels =0 private
Definition at line 209 of file VoxFoxTree.h.
The documentation for this class was generated from the following files:
VoxFoxTree.h
VoxFoxTree.cpp