Vox Fox: LeafNode Class Reference
LeafNode Class Reference
#include <LeafNode.h>
Public Member Functions
LeafNode ()
LeafNode (glm::vec3 _origin)
LeafNode (LeafNode const &_l)
LeafNode & operator= (LeafNode const &_l)
LeafNode operator+ (LeafNode const &_l) const
operator + Intersection set operator (retains LHS data)
LeafNode operator| (LeafNode const &_l) const
operator | Union operator set operator
LeafNode operator- (LeafNode const &_l) const
operator - Subtract set operator
bool addVoxel (glm::vec3 _position, Voxel _voxel)
addVoxel adds Voxel at specified _position to LeafNode
bool isVoxel (glm::vec3 _position) const
isVoxel checks if a Voxel is present within LeafNode at _position
glm::vec3 getOrigin () const
Public Attributes
std::array< char, 64 > m_VoxelMap
m_VoxelMap Each bit represents the presence of a voxel within the leafnode. 8*8*8 bits = 8*8 chars
std::vector< Voxel > m_VoxelData
m_VoxelData Voxel data for only the present voxels. Is variable.
int idx
int idy
int idz
Private Attributes
glm::vec3 m_origin
float unitVoxelLength = 0.01953125
float unitLeafLength = 0.15625
float m_primUnit = 10.0
float m_secUnit = 1.25
float m_leafUnit = 0.15625
float m_voxUnit = 0.01953125
Detailed Description
Definition at line 26 of file LeafNode.h.
Constructor & Destructor Documentation
LeafNode::LeafNode ()
Definition at line 3 of file LeafNode.cpp.
References m_VoxelMap.
 {
   m_VoxelMap.fill(0x00);
 }
LeafNode::LeafNode (glm::vec3 _origin)
Definition at line 7 of file LeafNode.cpp.
References idx, idy, idz, m_leafUnit, and m_VoxelMap.
                                   : m_origin(_origin)
 {
   idx = (int)(_origin[0]/m_leafUnit);
   idy = (int)(_origin[1]/m_leafUnit);
   idz = (int)(_origin[2]/m_leafUnit);
   m_VoxelMap.fill(0x00);
 }
LeafNode::LeafNode (LeafNode const & _l)
Definition at line 15 of file LeafNode.cpp.
References getOrigin(), idx, idy, idz, m_origin, m_VoxelData, and m_VoxelMap.
 {
   m_VoxelMap=l.m_VoxelMap;
   m_VoxelData=l.m_VoxelData;
   idx=l.idx;
   idy=l.idy;
   idz=l.idz;
   m_origin=l.getOrigin();
 }
Member Function Documentation
bool LeafNode::addVoxel (glm::vec3 _position, Voxel _voxel)
addVoxel adds Voxel at specified _position to LeafNode
Parameters
[in] _position position in worldspace of the voxel
[in] _data the information of the voxel to be added (see Voxel.h)
Returns
whether the voxel was successfully inserted or not
Definition at line 48 of file LeafNode.cpp.
References Voxel::index, m_origin, m_VoxelData, m_VoxelMap, m_voxUnit, and unitLeafLength.
 {
   glm::vec3 xyz = _position-m_origin;
   if(xyz.x>=0 && xyz.x<unitLeafLength && xyz.y>=0 && xyz.y<unitLeafLength && xyz.z>=0 && xyz.z<unitLeafLength )
   {
     Voxel insertVoxel = _voxel;
     xyz = floor(xyz/m_voxUnit);
     insertVoxel.index = (int) (xyz.x*8*8 + xyz.y*8 + xyz.z);
     if(!(m_VoxelMap[((int)xyz.x)*8 + (int)xyz.y] & (unsigned int) 1<<(int)xyz.z))
     {
       int count = 0;
       if(m_VoxelData.size()>0)
       {
         while(m_VoxelData[count].index<insertVoxel.index)
         {
           ++count;
           if(count+1>m_VoxelData.size())  break;
         }
       }
       m_VoxelData.insert(m_VoxelData.begin()+count,insertVoxel);
       m_VoxelMap[((int)xyz.x)*8 + (int)xyz.y] |= (unsigned int) 1<<(int)xyz.z;
     }
     // */
     return true;
   }
   else
   {
     return false;
   }
 }
glm::vec3 LeafNode::getOrigin () const inline
Definition at line 70 of file LeafNode.h.
References m_origin.
 {return m_origin; }
bool LeafNode::isVoxel (glm::vec3 _position) const
isVoxel checks if a Voxel is present within LeafNode at _position
Parameters
[in] _position position in worldspace of the voxel
Returns
if Voxel is present at _position
Definition at line 40 of file LeafNode.cpp.
References m_origin, m_VoxelMap, and m_voxUnit.
 {
   glm::vec3 xyz = _position-m_origin;
   xyz = floor(xyz/m_voxUnit);
   if(xyz.x<0 || xyz.x>7 || xyz.y<0|| xyz.y>7 || xyz.z<0|| xyz.z>7) return false;
   return m_VoxelMap[((int)xyz.x)*8 + (int)xyz.y] & (unsigned int) 1<<(int)xyz.z;
 }
LeafNode LeafNode::operator+ (LeafNode const & _l) const
operator + Intersection set operator (retains LHS data)
Parameters
[in] _l The other node to intersect with.
Returns
Intersected node that retains the LHS voxel data
Definition at line 80 of file LeafNode.cpp.
References LeafNode(), m_origin, m_VoxelData, and m_VoxelMap.
 {
   LeafNode retLeaf = LeafNode(m_origin);
   int count = 0;
   for(int i = 0; i<64; ++i)
   {
     retLeaf.m_VoxelMap[i] = m_VoxelMap[i] & _l.m_VoxelMap[i];
     for(int j =0 ; j<8; ++j)
     {
       if((m_VoxelMap[i] & (1<<j)) && (retLeaf.m_VoxelMap[i] & (1<<j)))
       {
         retLeaf.m_VoxelData.push_back(m_VoxelData[count]);
         count++;
       }
       if(m_VoxelMap[i] & (1<<j)) count++;
     }
   }
   return retLeaf;
 }
LeafNode LeafNode::operator- (LeafNode const & _l) const
operator - Subtract set operator
Parameters
[in] _l Node to subtract
Returns
Subtracted node
Definition at line 100 of file LeafNode.cpp.
References LeafNode(), m_origin, m_VoxelData, and m_VoxelMap.
 {
   LeafNode retLeaf = LeafNode(m_origin);
   int count =0;
   for(int i = 0; i<64; ++i)
   {
     retLeaf.m_VoxelMap[i] = m_VoxelMap[i] & ~(m_VoxelMap[i] & _l.m_VoxelMap[i]);
     for(int j =0 ; j<8; ++j)
     {
       if((retLeaf.m_VoxelMap[i] & (1<<j))&&(m_VoxelMap[i] & (1<<j)))
       {
         retLeaf.m_VoxelData.push_back(m_VoxelData[count]);
         count++;
       }
     }
   }
   return retLeaf;
 }
LeafNode & LeafNode::operator= (LeafNode const & _l)
Definition at line 25 of file LeafNode.cpp.
References getOrigin(), idx, idy, idz, m_origin, m_VoxelData, and m_VoxelMap.
 {
   if(this!=&_l)
   {
     m_VoxelMap=_l.m_VoxelMap;
     m_VoxelData=_l.m_VoxelData;
     idx=_l.idx;
     idy=_l.idy;
     idz=_l.idz;
     m_origin=_l.getOrigin();
     return *this;
   }
 }
LeafNode LeafNode::operator| (LeafNode const & _l) const
operator | Union operator set operator
Parameters
[in] _l The other node to union with
Returns
The unioned node
Definition at line 120 of file LeafNode.cpp.
References LeafNode(), m_origin, m_VoxelData, and m_VoxelMap.
 {
   LeafNode retLeaf = LeafNode(m_origin);
   for(int i = 0; i<64; ++i)
   {
     retLeaf.m_VoxelMap[i] = m_VoxelMap[i] | _l.m_VoxelMap[i];
   }
   int index1 =0;
   int index2 =0;
   bool done = false;
   while(!done)
   {
     if(m_VoxelData[index1].index<_l.m_VoxelData[index2].index)
     {
       retLeaf.m_VoxelData.push_back(m_VoxelData[index1]);
       index1++;
     }
     else if(m_VoxelData[index1].index>_l.m_VoxelData[index2].index)
     {
       retLeaf.m_VoxelData.push_back(_l.m_VoxelData[index2]);
       index2++;
     }
     else
     {
       retLeaf.m_VoxelData.push_back(m_VoxelData[index1]);
       index2++;
       index1++;
     }
     if(index2>=_l.m_VoxelData.size())
     {
       for(int i=index1; i<m_VoxelData.size(); ++i)
       {
         retLeaf.m_VoxelData.push_back(m_VoxelData[i]);
       }
       done=true;
     }
     else if(index1>=m_VoxelData.size())
     {
       for(int i=index2; i<_l.m_VoxelData.size(); ++i)
       {
         retLeaf.m_VoxelData.push_back(_l.m_VoxelData[i]);
       }
       done=true;
     }
   }
   return retLeaf;
 }
Member Data Documentation
int LeafNode::idx
Definition at line 84 of file LeafNode.h.
int LeafNode::idy
Definition at line 84 of file LeafNode.h.
int LeafNode::idz
Definition at line 84 of file LeafNode.h.
float LeafNode::m_leafUnit = 0.15625 private
Definition at line 91 of file LeafNode.h.
glm::vec3 LeafNode::m_origin private
Definition at line 86 of file LeafNode.h.
float LeafNode::m_primUnit = 10.0 private
Definition at line 89 of file LeafNode.h.
float LeafNode::m_secUnit = 1.25 private
Definition at line 90 of file LeafNode.h.
std::vector<Voxel> LeafNode::m_VoxelData
m_VoxelData Voxel data for only the present voxels. Is variable.
Definition at line 80 of file LeafNode.h.
std::array<char,64> LeafNode::m_VoxelMap
m_VoxelMap Each bit represents the presence of a voxel within the leafnode. 8*8*8 bits = 8*8 chars
Definition at line 75 of file LeafNode.h.
float LeafNode::m_voxUnit = 0.01953125 private
Definition at line 92 of file LeafNode.h.
float LeafNode::unitLeafLength = 0.15625 private
Definition at line 88 of file LeafNode.h.
float LeafNode::unitVoxelLength = 0.01953125 private
Definition at line 87 of file LeafNode.h.
The documentation for this class was generated from the following files:
LeafNode.h
LeafNode.cpp