Vox Fox: SecondaryNode Class Reference
SecondaryNode Class Reference
#include <SecondaryNode.h>
Public Member Functions
SecondaryNode ()
~SecondaryNode ()
SecondaryNode (glm::vec3 _origin)
SecondaryNode (SecondaryNode const &s)
SecondaryNode & operator= (SecondaryNode const &s)
SecondaryNode operator+ (SecondaryNode const &_s) const
operator + Union operator that takes two SecondaryNodes and gives SecondaryNode of union of both of them
SecondaryNode operator| (SecondaryNode const &_s) const
operator | Union operator that takes two SecondaryNodes and gives SecondaryNode of union of both of them
SecondaryNode operator- (SecondaryNode const &_s) const
operator - Subtract set operator
bool addVoxel (glm::vec3 _position, Voxel _voxel, LeafNode **io_leafAccessor)
addVoxel tries to add voxel to the SecondaryNode
bool isVoxel (glm::vec3 _position, LeafNode **io_leafAccessor) const
isVoxel checks if a Voxel is present within the SecondaryNode at _position
glm::vec3 getOrigin () const
getOrigin returns the origin vector of node (minimum point in Node)
bool isLeaf (glm::vec3 _position, LeafNode **o_leaf) const
isLeaf Checks to see if the leaf at the _position is within m_leafChildren of the SecondaryNode
Public Attributes
std::vector< LeafNode * > m_leafChildren
m_leafChildren vector of pointers to the LeafNode children
int idx
int idy
int idz
Private Attributes
glm::vec3 m_origin
float m_primUnit = 10.0
float m_secUnit = 1.25
float m_leafUnit = 0.15625
float m_voxUnit = 0.01953125
Detailed Description
Definition at line 19 of file SecondaryNode.h.
Constructor & Destructor Documentation
SecondaryNode::SecondaryNode ()
Definition at line 3 of file SecondaryNode.cpp.
 {
 }
SecondaryNode::~SecondaryNode ()
Definition at line 8 of file SecondaryNode.cpp.
References m_leafChildren.
 {
   for(auto & l : m_leafChildren)
   {
     delete l;
   }
   m_leafChildren.clear();
 }
SecondaryNode::SecondaryNode (glm::vec3 _origin)
Definition at line 17 of file SecondaryNode.cpp.
References idx, idy, idz, and m_secUnit.
                                             : m_origin(_origin)
 {
   idx = (int)(_origin[0]/m_secUnit);
   idy = (int)(_origin[1]/m_secUnit);
   idz = (int)(_origin[2]/m_secUnit);
 }
SecondaryNode::SecondaryNode (SecondaryNode const & s)
Member Function Documentation
bool SecondaryNode::addVoxel (glm::vec3 _position, Voxel _voxel, LeafNode ** io_leafAccessor)
addVoxel tries to add voxel to the SecondaryNode
Parameters
[in] _position position in worldspace of the voxel
[in] _voxel the information of the voxel to be added
[in,out] io_leafAccessor the leaf accessor to change (last accessed LeafNode)
Returns
if _position is within the SecondaryNode and is added (used for accessors in Root::addVoxel(..))
Definition at line 73 of file SecondaryNode.cpp.
References m_leafChildren, m_leafUnit, m_origin, and m_secUnit.
 {
   for (auto &leaf : m_leafChildren) // access by reference to avoid copying
       {
         if(_position[0]<leaf->getOrigin()[0] || _position[0]>=leaf->getOrigin()[0]+m_leafUnit) continue;
         if(_position[1]<leaf->getOrigin()[1] || _position[1]>=leaf->getOrigin()[1]+m_leafUnit) continue;
         if(_position[2]<leaf->getOrigin()[2] || _position[2]>=leaf->getOrigin()[2]+m_leafUnit) continue;
         //if(glm::all(glm::lessThan(_position,leaf->getOrigin)) && glm::all(glm::greaterThanEqual(_position,)))
         leaf->addVoxel(_position,_voxel);
         (*o_leafAccessor)=leaf;
         return true;
       }
   glm::vec3 newOrigin = floor(_position/m_leafUnit)*m_leafUnit;
   if(_position[0]>=m_origin[0] && _position[0]<m_origin[0]+m_secUnit &&
     _position[1]>=m_origin[1] && _position[1]<m_origin[1]+m_secUnit &&
     _position[2]>=m_origin[2] && _position[2]<m_origin[2]+m_secUnit)
   {
     m_leafChildren.push_back(new LeafNode(newOrigin));
     m_leafChildren.back()->addVoxel(_position,_voxel);
     (*o_leafAccessor)=m_leafChildren.back();
     return true;
   }
   else
   {
     return false;
   }
 }
glm::vec3 SecondaryNode::getOrigin () const inline
getOrigin returns the origin vector of node (minimum point in Node)
Returns
origin vector of node
Definition at line 71 of file SecondaryNode.h.
References m_origin.
 {return m_origin; }
bool SecondaryNode::isLeaf (glm::vec3 _position, LeafNode ** o_leaf) const
isLeaf Checks to see if the leaf at the _position is within m_leafChildren of the SecondaryNode
Parameters
[in] _position The position which the LeafNode searched for occupies
[out] o_leaf If there is a leaf, the leaf is deposited in this double pointer (as a pointer).
Returns
True if leaf is present at _position
Definition at line 105 of file SecondaryNode.cpp.
References getOrigin(), m_leafChildren, and m_leafUnit.
 {
   for (int i =0; i<m_leafChildren.size(); ++i) // access by reference to avoid copying
   {
     if(_position[0]<m_leafChildren[i]->getOrigin()[0] || _position[0]>=m_leafChildren[i]->getOrigin()[0]+m_leafUnit) continue;
     if(_position[1]<m_leafChildren[i]->getOrigin()[1] || _position[1]>=m_leafChildren[i]->getOrigin()[1]+m_leafUnit) continue;
     if(_position[2]<m_leafChildren[i]->getOrigin()[2] || _position[2]>=m_leafChildren[i]->getOrigin()[2]+m_leafUnit) continue;
     *o_leaf = m_leafChildren[i];
     return true;
   }
   return false;
 }
bool SecondaryNode::isVoxel (glm::vec3 _position, LeafNode ** io_leafAccessor) const
isVoxel checks if a Voxel is present within the SecondaryNode at _position
Parameters
[in] _position position in worldspace of the voxel
[in,out] io_leafAccessor the leaf accessor to change (last accessed LeafNode)
Returns
if Voxel is present at _position
Definition at line 60 of file SecondaryNode.cpp.
References m_leafChildren, and m_leafUnit.
 {
   for (auto &leaf : m_leafChildren) // access by reference to avoid copying
       {
         if(_position[0]<leaf->getOrigin()[0] || _position[0]>=leaf->getOrigin()[0]+m_leafUnit) continue;
         if(_position[1]<leaf->getOrigin()[1] || _position[1]>=leaf->getOrigin()[1]+m_leafUnit) continue;
         if(_position[2]<leaf->getOrigin()[2] || _position[2]>=leaf->getOrigin()[2]+m_leafUnit) continue;
         (*_leafAccessor)=leaf;
         return leaf->isVoxel(_position);
       }
   return false;
 }
SecondaryNode SecondaryNode::operator+ (SecondaryNode const & _s) const
operator + Union operator that takes two SecondaryNodes and gives SecondaryNode of union of both of them
Parameters
[in] _s RHS of operator
Returns
Union of RHS and LHS SecondaryNode
Definition at line 119 of file SecondaryNode.cpp.
References m_leafChildren, m_origin, and SecondaryNode().
 {
   SecondaryNode retSec = SecondaryNode(m_origin);
   // Leafs are not in order so cannot use jindex trick in + in LeafNode
   for(const auto &i : m_leafChildren)
   {
     for(const auto &j : _s.m_leafChildren)
     {
       if(i->idx==j->idx && i->idy==j->idy && i->idz==j->idz)
       {
         retSec.m_leafChildren.push_back(new LeafNode(*i+*j));
       }
     }
   }
   return retSec;
 }
SecondaryNode SecondaryNode::operator- (SecondaryNode const & _s) const
operator - Subtract set operator
Parameters
[in] _s SecondaryNode to subtract
Returns
Subtracted SecondaryNode
Definition at line 136 of file SecondaryNode.cpp.
References m_leafChildren, m_origin, LeafNode::m_VoxelData, and SecondaryNode().
 {
   SecondaryNode retSec = SecondaryNode(m_origin);
   for(const auto &i : m_leafChildren)
   {
     bool found = false;
     for(const auto &j : _s.m_leafChildren)
     {
       if(i->idx==j->idx && i->idy==j->idy && i->idz==j->idz)
       {
         LeafNode testLeaf = LeafNode(*i-*j);
         // testLeaf could be empty. We test for that.
         // if empty crashes other functions. We always assume that nodes are not empty (flaw?)
         if(testLeaf.m_VoxelData.size()!=0) retSec.m_leafChildren.push_back(new LeafNode(testLeaf));
         found = true;
         break;
       }
     }
     if(!found)
     {
       retSec.m_leafChildren.push_back(new LeafNode(*i));
     }
   }
   return retSec;
 }
SecondaryNode & SecondaryNode::operator= (SecondaryNode const & s)
Definition at line 36 of file SecondaryNode.cpp.
References getOrigin(), idx, idy, idz, m_leafChildren, and m_origin.
 {
   if(this!=&s)
   {
     // DELETE OLD DATA
     for(auto & l : m_leafChildren)
     {
       delete l;
     }
     m_leafChildren.clear();
     // ASSIGN NEW DATA
     for(auto & i : s.m_leafChildren)
     {
       m_leafChildren.push_back(new LeafNode(*i));
     }
     m_origin=s.getOrigin();
     idx = s.idx;
     idy = s.idy;
     idz = s.idz;
   }
   return *this;
 }
SecondaryNode SecondaryNode::operator| (SecondaryNode const & _s) const
operator | Union operator that takes two SecondaryNodes and gives SecondaryNode of union of both of them
Parameters
[in] _s RHS of operator
Returns
Union of RHS and LHS SecondaryNode
Definition at line 163 of file SecondaryNode.cpp.
References m_leafChildren, m_origin, and SecondaryNode().
 {
   SecondaryNode retSec = SecondaryNode(m_origin);
   std::vector<bool> jfound;
   for(int i =0 ; i<m_leafChildren.size(); ++i)
   {
     jfound.push_back(false);
   }
   for(const auto &i : _s.m_leafChildren)
   {
     bool found = false;
     for(int j =0; j<m_leafChildren.size(); ++j)
     {
       if(i->idx==m_leafChildren[j]->idx && i->idy==m_leafChildren[j]->idy && i->idz==m_leafChildren[j]->idz)
       {
         retSec.m_leafChildren.push_back(new LeafNode(*m_leafChildren[j]|*i));
         jfound[j]=true;
         found = true;
         break;
       }
     }
     if(!found)
     {
       retSec.m_leafChildren.push_back(new LeafNode(*i));
     }
   }
   for(int i =0 ; i<jfound.size(); ++i)
   {
     if(!jfound[i]) retSec.m_leafChildren.push_back(new LeafNode(*m_leafChildren[i]));
   }
   return retSec;
 }
Member Data Documentation
int SecondaryNode::idx
Definition at line 88 of file SecondaryNode.h.
int SecondaryNode::idy
Definition at line 88 of file SecondaryNode.h.
int SecondaryNode::idz
Definition at line 88 of file SecondaryNode.h.
std::vector<LeafNode *> SecondaryNode::m_leafChildren
m_leafChildren vector of pointers to the LeafNode children
Definition at line 84 of file SecondaryNode.h.
float SecondaryNode::m_leafUnit = 0.15625 private
Definition at line 94 of file SecondaryNode.h.
glm::vec3 SecondaryNode::m_origin private
Definition at line 91 of file SecondaryNode.h.
float SecondaryNode::m_primUnit = 10.0 private
Definition at line 92 of file SecondaryNode.h.
float SecondaryNode::m_secUnit = 1.25 private
Definition at line 93 of file SecondaryNode.h.
float SecondaryNode::m_voxUnit = 0.01953125 private
Definition at line 95 of file SecondaryNode.h.
The documentation for this class was generated from the following files:
SecondaryNode.h
SecondaryNode.cpp