#############################################################################
# Makefile for building: VoxFox
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  VoxFox.pro
# Template: app
# Command: /Users/Tom/Qt2/5.8/clang_64/bin/qmake -o Makefile VoxFox.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -msse -msse2 -msse3 -arch x86_64 -g -std=gnu++11 -Wall -W -Wno-unused-parameter -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/usr/local/include -I/usr/local/Cellar -I/usr/local/lib -I/usr/local/include -I../../../NGL/include -I../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers -I../../../Qt2/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers -I../../../Qt2/5.8/clang_64/lib/QtCore.framework/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt2/5.8/clang_64/mkspecs/macx-clang -F/Users/Tom/Qt2/5.8/clang_64/lib
QMAKE         = /Users/Tom/Qt2/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VoxFox1.0.0
DISTDIR = /Users/Tom/Documents/GitHubStuff/VoxFox/obj/VoxFox1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,@loader_path/L/Users/Tom/NGL/lib -Wl,-rpath,/Users/Tom/NGL/lib -Wl,-rpath,/Users/Tom/Qt2/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Tom/Qt2/5.8/clang_64/lib -framework OpenGL -framework GLUT -L/usr/local/lib -L/Users/Tom/NGL/lib -l NGL -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/NGLScene.cpp \
		src/NGLSceneMouseControls.cpp \
		src/main.cpp \
		src/LeafNode.cpp \
		src/RootNode.cpp \
		src/SecondaryNode.cpp \
		src/PrimaryNode.cpp \
		src/PolyToVoxel.cpp moc/moc_NGLScene.cpp
OBJECTS       = obj/NGLScene.o \
		obj/NGLSceneMouseControls.o \
		obj/main.o \
		obj/LeafNode.o \
		obj/RootNode.o \
		obj/SecondaryNode.o \
		obj/PrimaryNode.o \
		obj/PolyToVoxel.o \
		obj/moc_NGLScene.o
DIST          = ../../../Qt2/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt2/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Qt2/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Qt2/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt2/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt2/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt2/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../NGL/UseNGL.pri \
		../../../Qt2/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/uic.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/lex.prf \
		VoxFox.pro include/NGLScene.h \
		include/WindowParams.h \
		include/RootNode.h \
		include/LeafNode.h \
		include/SecondaryNode.h \
		include/PrimaryNode.h \
		include/PolyToVoxel.h src/NGLScene.cpp \
		src/NGLSceneMouseControls.cpp \
		src/main.cpp \
		src/LeafNode.cpp \
		src/RootNode.cpp \
		src/SecondaryNode.cpp \
		src/PrimaryNode.cpp \
		src/PolyToVoxel.cpp
QMAKE_TARGET  = VoxFox
DESTDIR       = 
TARGET        = VoxFox


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VoxFox.pro .qmake.cache ../../../Qt2/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt2/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt2/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Qt2/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Qt2/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Qt2/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt2/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt2/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt2/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt2/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../NGL/UseNGL.pri \
		../../../Qt2/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/uic.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Qt2/5.8/clang_64/mkspecs/features/lex.prf \
		VoxFox.pro \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		../../../Qt2/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt2/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile VoxFox.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt2/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt2/5.8/clang_64/mkspecs/qdevice.pri:
../../../Qt2/5.8/clang_64/mkspecs/features/device_config.prf:
../../../Qt2/5.8/clang_64/mkspecs/common/unix.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/mac.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/macx.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/sanitize.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/clang.conf:
../../../Qt2/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt2/5.8/clang_64/mkspecs/qconfig.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt2/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt2/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/qt_config.prf:
../../../Qt2/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt2/5.8/clang_64/mkspecs/features/spec_post.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/toolchain.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/default_pre.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../../NGL/UseNGL.pri:
../../../Qt2/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/default_post.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/warn_on.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/qt.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/resources.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/moc.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/uic.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/file_copies.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/exceptions.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/yacc.prf:
../../../Qt2/5.8/clang_64/mkspecs/features/lex.prf:
VoxFox.pro:
../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
../../../Qt2/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt2/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt2/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile VoxFox.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt2/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/NGLScene.h include/WindowParams.h include/RootNode.h include/LeafNode.h include/SecondaryNode.h include/PrimaryNode.h include/PolyToVoxel.h $(DISTDIR)/
	$(COPY_FILE) --parents src/NGLScene.cpp src/NGLSceneMouseControls.cpp src/main.cpp src/LeafNode.cpp src/RootNode.cpp src/SecondaryNode.cpp src/PrimaryNode.cpp src/PolyToVoxel.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: ../../../Qt2/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -msse -msse2 -msse3 -arch x86_64 -g -std=gnu++11 -Wall -W -Wno-unused-parameter -dM -E -o moc/moc_predefs.h ../../../Qt2/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_NGLScene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_NGLScene.cpp
moc/moc_NGLScene.cpp: include/WindowParams.h \
		../../../NGL/include/ngl/Camera.h \
		../../../NGL/include/ngl/Types.h \
		../../../NGL/include/ngl/glew.h \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/QGLContext \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../NGL/include/ngl/Vec4.h \
		../../../NGL/include/ngl/Vec2.h \
		../../../NGL/include/ngl/Vec3.h \
		../../../NGL/include/ngl/Mat4.h \
		../../../NGL/include/ngl/RibExport.h \
		../../../NGL/include/ngl/Plane.h \
		../../../NGL/include/ngl/AABB.h \
		../../../NGL/include/ngl/BBox.h \
		../../../NGL/include/ngl/AbstractVAO.h \
		../../../NGL/include/ngl/Colour.h \
		../../../NGL/include/ngl/Light.h \
		../../../NGL/include/ngl/Text.h \
		../../../NGL/include/ngl/VAOFactory.h \
		../../../NGL/include/ngl/SimpleVAO.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		include/RootNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h \
		include/LeafNode.h \
		include/PrimaryNode.h \
		include/SecondaryNode.h \
		include/NGLScene.h \
		moc/moc_predefs.h \
		../../../Qt2/5.8/clang_64/bin/moc
	/Users/Tom/Qt2/5.8/clang_64/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/Users/Tom/Qt2/5.8/clang_64/mkspecs/macx-clang -I/Users/Tom/Documents/GitHubStuff/VoxFox -I/Users/Tom/Documents/GitHubStuff/VoxFox/include -I/usr/local/include -I/usr/local/Cellar -I/usr/local/lib -I/usr/local/include -I/Users/Tom/NGL/include -I/Users/Tom/Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers -I/Users/Tom/Qt2/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/Tom/Qt2/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/Tom/Qt2/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/Tom/Qt2/5.8/clang_64/lib include/NGLScene.h -o moc/moc_NGLScene.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/NGLScene.o: src/NGLScene.cpp include/NGLScene.h \
		include/WindowParams.h \
		../../../NGL/include/ngl/Camera.h \
		../../../NGL/include/ngl/Types.h \
		../../../NGL/include/ngl/glew.h \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/QGLContext \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../NGL/include/ngl/Vec4.h \
		../../../NGL/include/ngl/Vec2.h \
		../../../NGL/include/ngl/Vec3.h \
		../../../NGL/include/ngl/Mat4.h \
		../../../NGL/include/ngl/RibExport.h \
		../../../NGL/include/ngl/Plane.h \
		../../../NGL/include/ngl/AABB.h \
		../../../NGL/include/ngl/BBox.h \
		../../../NGL/include/ngl/AbstractVAO.h \
		../../../NGL/include/ngl/Colour.h \
		../../../NGL/include/ngl/Light.h \
		../../../NGL/include/ngl/Text.h \
		../../../NGL/include/ngl/VAOFactory.h \
		../../../NGL/include/ngl/SimpleVAO.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		include/RootNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h \
		include/LeafNode.h \
		include/PrimaryNode.h \
		include/SecondaryNode.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../NGL/include/ngl/Material.h \
		../../../NGL/include/ngl/NGLInit.h \
		../../../NGL/include/ngl/Singleton.h \
		../../../NGL/include/ngl/VAOPrimitives.h \
		../../../NGL/include/ngl/NGLStream.h \
		../../../NGL/include/ngl/ShaderLib.h \
		../../../NGL/include/ngl/Shader.h \
		../../../NGL/include/ngl/ShaderProgram.h \
		../../../NGL/include/ngl/Util.h \
		../../../NGL/include/ngl/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/NGLSceneMouseControls.o: src/NGLSceneMouseControls.cpp include/NGLScene.h \
		include/WindowParams.h \
		../../../NGL/include/ngl/Camera.h \
		../../../NGL/include/ngl/Types.h \
		../../../NGL/include/ngl/glew.h \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/QGLContext \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../NGL/include/ngl/Vec4.h \
		../../../NGL/include/ngl/Vec2.h \
		../../../NGL/include/ngl/Vec3.h \
		../../../NGL/include/ngl/Mat4.h \
		../../../NGL/include/ngl/RibExport.h \
		../../../NGL/include/ngl/Plane.h \
		../../../NGL/include/ngl/AABB.h \
		../../../NGL/include/ngl/BBox.h \
		../../../NGL/include/ngl/AbstractVAO.h \
		../../../NGL/include/ngl/Colour.h \
		../../../NGL/include/ngl/Light.h \
		../../../NGL/include/ngl/Text.h \
		../../../NGL/include/ngl/VAOFactory.h \
		../../../NGL/include/ngl/SimpleVAO.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		include/RootNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h \
		include/LeafNode.h \
		include/PrimaryNode.h \
		include/SecondaryNode.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLSceneMouseControls.o src/NGLSceneMouseControls.cpp

obj/main.o: src/main.cpp include/NGLScene.h \
		include/WindowParams.h \
		../../../NGL/include/ngl/Camera.h \
		../../../NGL/include/ngl/Types.h \
		../../../NGL/include/ngl/glew.h \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/QGLContext \
		../../../Qt2/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../NGL/include/ngl/Vec4.h \
		../../../NGL/include/ngl/Vec2.h \
		../../../NGL/include/ngl/Vec3.h \
		../../../NGL/include/ngl/Mat4.h \
		../../../NGL/include/ngl/RibExport.h \
		../../../NGL/include/ngl/Plane.h \
		../../../NGL/include/ngl/AABB.h \
		../../../NGL/include/ngl/BBox.h \
		../../../NGL/include/ngl/AbstractVAO.h \
		../../../NGL/include/ngl/Colour.h \
		../../../NGL/include/ngl/Light.h \
		../../../NGL/include/ngl/Text.h \
		../../../NGL/include/ngl/VAOFactory.h \
		../../../NGL/include/ngl/SimpleVAO.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		../../../Qt2/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		include/RootNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h \
		include/LeafNode.h \
		include/PrimaryNode.h \
		include/SecondaryNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/LeafNode.o: src/LeafNode.cpp include/LeafNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/LeafNode.o src/LeafNode.cpp

obj/RootNode.o: src/RootNode.cpp include/RootNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h \
		include/LeafNode.h \
		include/PrimaryNode.h \
		include/SecondaryNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/RootNode.o src/RootNode.cpp

obj/SecondaryNode.o: src/SecondaryNode.cpp include/SecondaryNode.h \
		include/LeafNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/SecondaryNode.o src/SecondaryNode.cpp

obj/PrimaryNode.o: src/PrimaryNode.cpp include/PrimaryNode.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h \
		include/LeafNode.h \
		include/SecondaryNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PrimaryNode.o src/PrimaryNode.cpp

obj/PolyToVoxel.o: src/PolyToVoxel.cpp include/PolyToVoxel.h \
		lib/glm/glm/glm.hpp \
		lib/glm/glm/detail/_fixes.hpp \
		lib/glm/glm/fwd.hpp \
		lib/glm/glm/detail/type_int.hpp \
		lib/glm/glm/detail/setup.hpp \
		lib/glm/glm/simd/platform.h \
		lib/glm/glm/detail/type_float.hpp \
		lib/glm/glm/detail/type_vec.hpp \
		lib/glm/glm/detail/precision.hpp \
		lib/glm/glm/detail/type_mat.hpp \
		lib/glm/glm/vec2.hpp \
		lib/glm/glm/detail/type_vec2.hpp \
		lib/glm/glm/detail/_swizzle.hpp \
		lib/glm/glm/detail/_swizzle_func.hpp \
		lib/glm/glm/detail/type_vec2.inl \
		lib/glm/glm/vec3.hpp \
		lib/glm/glm/detail/type_vec3.hpp \
		lib/glm/glm/detail/type_vec3.inl \
		lib/glm/glm/vec4.hpp \
		lib/glm/glm/detail/type_vec4.hpp \
		lib/glm/glm/detail/type_vec4.inl \
		lib/glm/glm/detail/type_vec4_simd.inl \
		lib/glm/glm/mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.hpp \
		lib/glm/glm/detail/type_mat2x2.inl \
		lib/glm/glm/detail/func_matrix.hpp \
		lib/glm/glm/mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.hpp \
		lib/glm/glm/detail/type_mat2x3.inl \
		lib/glm/glm/mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.hpp \
		lib/glm/glm/detail/type_mat2x4.inl \
		lib/glm/glm/mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.hpp \
		lib/glm/glm/detail/type_mat3x2.inl \
		lib/glm/glm/mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.hpp \
		lib/glm/glm/detail/type_mat3x3.inl \
		lib/glm/glm/mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.hpp \
		lib/glm/glm/detail/type_mat3x4.inl \
		lib/glm/glm/mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.hpp \
		lib/glm/glm/detail/type_mat4x2.inl \
		lib/glm/glm/mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.hpp \
		lib/glm/glm/detail/type_mat4x3.inl \
		lib/glm/glm/mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.hpp \
		lib/glm/glm/detail/type_mat4x4.inl \
		lib/glm/glm/detail/type_mat4x4_simd.inl \
		lib/glm/glm/detail/func_matrix.inl \
		lib/glm/glm/geometric.hpp \
		lib/glm/glm/detail/func_geometric.hpp \
		lib/glm/glm/detail/func_geometric.inl \
		lib/glm/glm/detail/func_exponential.hpp \
		lib/glm/glm/detail/type_vec1.hpp \
		lib/glm/glm/detail/type_vec1.inl \
		lib/glm/glm/detail/func_exponential.inl \
		lib/glm/glm/detail/func_vector_relational.hpp \
		lib/glm/glm/detail/func_vector_relational.inl \
		lib/glm/glm/detail/func_vector_relational_simd.inl \
		lib/glm/glm/detail/_vectorize.hpp \
		lib/glm/glm/detail/func_exponential_simd.inl \
		lib/glm/glm/simd/exponential.h \
		lib/glm/glm/detail/func_common.hpp \
		lib/glm/glm/detail/func_common.inl \
		lib/glm/glm/detail/func_common_simd.inl \
		lib/glm/glm/simd/common.h \
		lib/glm/glm/detail/func_geometric_simd.inl \
		lib/glm/glm/simd/geometric.h \
		lib/glm/glm/detail/func_matrix_simd.inl \
		lib/glm/glm/simd/matrix.h \
		lib/glm/glm/trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.hpp \
		lib/glm/glm/detail/func_trigonometric.inl \
		lib/glm/glm/detail/func_trigonometric_simd.inl \
		lib/glm/glm/exponential.hpp \
		lib/glm/glm/common.hpp \
		lib/glm/glm/packing.hpp \
		lib/glm/glm/detail/func_packing.hpp \
		lib/glm/glm/detail/func_packing.inl \
		lib/glm/glm/detail/type_half.hpp \
		lib/glm/glm/detail/type_half.inl \
		lib/glm/glm/detail/func_packing_simd.inl \
		lib/glm/glm/matrix.hpp \
		lib/glm/glm/vector_relational.hpp \
		lib/glm/glm/integer.hpp \
		lib/glm/glm/detail/func_integer.hpp \
		lib/glm/glm/detail/func_integer.inl \
		lib/glm/glm/detail/func_integer_simd.inl \
		lib/glm/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PolyToVoxel.o src/PolyToVoxel.cpp

obj/moc_NGLScene.o: moc/moc_NGLScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_NGLScene.o moc/moc_NGLScene.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

